// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlfZEWKa7spsWLIIkqHhhoz7sWVWBhh3o',
    appId: '1:1051669991982:web:27b61f1aa1790c91c4c5bf',
    messagingSenderId: '1051669991982',
    projectId: 'funminton-app',
    authDomain: 'funminton-app.firebaseapp.com',
    storageBucket: 'funminton-app.firebasestorage.app',
    measurementId: 'G-J5MWZGJF62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztzvxw0pFYGnX9tneAEcmkNMv6Wuth8I',
    appId: '1:1051669991982:android:7f01f3bebde575e7c4c5bf',
    messagingSenderId: '1051669991982',
    projectId: 'funminton-app',
    storageBucket: 'funminton-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYBfW9siKcaFYebpVILpkpA1DbTrmLkrU',
    appId: '1:1051669991982:ios:ed8ca0d317828a12c4c5bf',
    messagingSenderId: '1051669991982',
    projectId: 'funminton-app',
    storageBucket: 'funminton-app.firebasestorage.app',
    iosBundleId: 'com.example.morningInsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYBfW9siKcaFYebpVILpkpA1DbTrmLkrU',
    appId: '1:1051669991982:ios:ed8ca0d317828a12c4c5bf',
    messagingSenderId: '1051669991982',
    projectId: 'funminton-app',
    storageBucket: 'funminton-app.firebasestorage.app',
    iosBundleId: 'com.example.morningInsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlfZEWKa7spsWLIIkqHhhoz7sWVWBhh3o',
    appId: '1:1051669991982:web:e6ca1ac618ee6da6c4c5bf',
    messagingSenderId: '1051669991982',
    projectId: 'funminton-app',
    authDomain: 'funminton-app.firebaseapp.com',
    storageBucket: 'funminton-app.firebasestorage.app',
    measurementId: 'G-6QFSZE4Q1F',
  );
}
